### ISSUE TITLE
imxvpudec leaking memory when playing h264 interlaced content

### ISSUE THREAD

**Issue by isaacrj** [Freescale/gstreamer-imx#54]
Hi again!

I'm trying to include DVB-T capabilities into our software and I noticed something odd: I can play nicely any type of content (720p, 720i, 1280p, 1080i...) but, when playing H264 interlaced, the gstreamer pipeline starts to leak memory. It leaks 1Mb each 3-4 seconds at the beginning and then it starts leaking faster and faster. After 20 to 30min of playing, the system runs out of memory and crashes.

To rule out any DVB-T tunning or signal quality issues, I captured a few seconds of the TS stream in each of the transponders I'm using, uploaded them to my host computer and checked them out to make sure that they were OK. Then I run another round of tests using the captured files as source to rule out any issues that could be derived from using a live source, and these are my results:

`Playing H264 1280x720@25p. Does NOT leak:`
`gst-launch-1.0 filesrc location=Transponder01.ts ! tsdemux name="demux" program-number=514 demux.video_012d ! queue  ! h264parse ! queue ! imxvpudec ! queue ! imxipuvideosink`

`Playing MPEG2 720x576@50i. Does NOT leak:`
`gst-launch-1.0 filesrc location=Transponder01.ts ! tsdemux name="demux" program-number=510 demux.video_0065 ! queue  ! mpegvideoparse ! queue ! imxvpudec ! queue ! imxipuvideosink`

`Examples playing H264 1920x1080@50i. They both leak:`
`gst-launch-1.0 filesrc location=Transponder05.ts ! tsdemux name="demux" program-number=190 demux.video_05dd ! queue  ! h264parse ! queue ! imxvpudec ! queue ! imxipuvideosink`
`gst-launch-1.0 filesrc location=Transponder05.ts ! tsdemux name="demux" program-number=191 demux.video_06a5 ! queue  ! h264parse ! queue ! imxvpudec ! queue ! imxipuvideosink`

If I use avdec_h264 instead of imxvpudec, the pipelines drop a lot of frames, but they don't leak. Also, when playing content with GST_DEBUG=imx*:5, the "leaky" pipelines produce a lot of
`0:00:07.532020585  2092  0x13dd5b0 DEBUG              imxvpudec ../src/vpu/decoder/decoder.c:1097:gst_imx_vpu_dec_handle_frame:<imxvpudec0> need more input`

I can reproduce the issue with any combination of gstreamer 1.2.1 or 1.4.1 with gstreamer-imx 0.10.2, 0.11.1 or git.

I have uploaded both transponder captures, so you can run the pipelines and reproduce the issue. Please, find them here: [Transponder01.ts](https://dl.dropboxusercontent.com/u/44876279/Transponder01.ts) [Transponder05.ts](https://dl.dropboxusercontent.com/u/44876279/Transponder05.ts)

I can upload bigger captures should you need more pipeline runtime.

I know this is a tough one. If you can find some time to look at it I'll be very grateful.

Best regards,
Isaac

**Comment by isaacrj-scio** [comment]
Trying to track down where exactly is gstreamer leaking memory, I tried this pipeline:
 `gst-launch-1.0 filesrc location=Transponder05.ts ! tsdemux name="demux" program-number=190 demux.video_05dd ! queue ! h264parse ! queue` **leaky=2** `! imxvpudec ! queue ! imxipuvideosink`

This is effectively telling the queue to drop buffers instead of blocking if it gets filled up. With this configuration, the video renders horribly and full of artifacts due to the buffer dropping but the leak does not occur any more. My guess is that maybe imxvpudec is not leaking memory at all, maybe it is just consuming buffers too slowly and it is causing the queues upstream to fill up, and it is this filling up what would look like a memory leak when using `top` to monitor memory usage.

**Comment by dv1** [comment]
This might indeed be. One fundamental problem with the way the VPU works is that I have to sometimes block the data flow with a condition variable, since the VPU buffer pool is fixed. It is initialized once, when the VPU decoder is created. Afterwards, it is not possible to allocate additional buffers on the fly. If therefore downstream consumes the buffers slowly, but also buffers a lot of them, it is possible that all of the VPU buffers are queued up somewhere downstream. The VPU then has no free buffers to decode into, and the imxvpudec element therefore has to wait until downstream consumes one of the buffers.

**Comment by isaacrj-scio** [comment]
Thank you for your reply, this one is driving me nuts and any tiny piece of advice is greatly appreciated.

I run another round of tests, gradually increasing the value of `imxvpudec num-additional-buffers`, but I still get the same results: the pipeline leaks memory regardless of the value of `num-additional-buffers`, but it does not leak at all if I put the `leaky=2` modifier to the queue inmediately upstream of imvpudec, also reagardless of the `num-additional-buffers` value. 

What is really puzzling me is that the pipelines play nicely despite the leaking and the fact that imxvpudec is complaining all the time about not having enough input (when it seems that it is actually having more than it can consume in time). It is also odd that this things only happen when decoding H264 **interlaced** content. Any other channels, using H264 progressive or MPEG2 play nicely and without leaks. Unfortunately, almost all the HDTV channels here in Spain do use H264 interlaced in their video streams.

As I said before, any tiny piece of advice will be greatly appreciated. Also, if you finally can find the time to have a look at this and feel like you need bigger captures, just tell me. At the very least, you can see what spanish TV looks like ;-)

Thank you again.

**Comment by dv1** [comment]
The interlaced part may be the key. The 0x109 "need more input" hints at something there. Perhaps I am getting only parts of the frame at once. videodecoder logs show that unfinished frames are piling up, which makes sense if 0x109 keeps appearing all the time. I've never had this behavior before, I need to see what the correct course of action is there. If the 0x109 frames can simply be finished right then and there, then its easy. But I need to be sure. Time to look at transport streams a bit more..

**Comment by dv1** [comment]
OK, I think I have a first working fix. It turns out that every second frame causes 0x109 to appear. Looking at gst-libav, its decoder finishes a frame, and then simply discards any unfinished frames which (a) are older than the DTS of the finished frame and (b) have never been picked by libav for decoding. Turn up the logs when you use avdec_h264, and you'll see a lot of "discarding ghost frame" lines. By replicating this discarding, I managed to get rid of the memleaks. This needs significant testing though.

It can be done in imxvpudec by setting the DECODE_ONLY flag on every incoming frame in handle_frame, and unsetting the flag only when a frame is picked for decoding (in the VPU_DEC_ONE_FRM_CONSUMED block, and right after the get_oldest_frame() calls). Then, prior to actually finishing a frame, all frames in the gst_frame_table are iterated over. If there is one frame that has the DECODE_ONLY flag set, discard. A commit with this fix will follow.

**Comment by isaacrj-scio** [comment]
Please let me know when the commit is done, so I can help with the testing.
As always, thanks a lot.

**Comment by dv1** [comment]
Is it OK to post these TS links in the GStreamer IRC channel? There is a little confusion about why this issue is even happening in the first place (that is, why the videodecoder doesn't get full frames).

**Comment by isaacrj-scio** [comment]
There should be no problem, they are captures of publicly broadcasted TV feeds...

**Comment by isaacrj-scio** [comment]
Hi, 

   Is there any chance you could send me a patch with this working fix? I would apply it to master and run another round of tests on it.

   Even if it is not working 100% perfect, it would help me a lot to be able to demo the DVB-T capabilites using HDTV channels.

Thanks!

**Comment by dv1** [comment]
I'm nearly done with the fix, and expect it to be ready later today.

**Comment by isaacrj-scio** [comment]
Ok, thanks a lot.

**Comment by isaacrj-scio** [comment]
I applied the patch to master and run another round of tests. HDTV channels are not leaking now and the play OK.

Bad news are that all the other channels (H264 progressive, MPEG2 interlaced) are now broken: I'm get a SIGSEGV within the first 5 seconds of play. I have run a couple of tests with `GST_EXPORT=imx*:5` and I can see some XXXX marked debug messages that appear right before the SIGSEGV.  Here are the logs should you need them:

[h264-progressive.log](https://dl.dropboxusercontent.com/u/44876279/h264-progressive.log)
[mpeg2-interlaced.log](https://dl.dropboxusercontent.com/u/44876279/mpeg2-interlaced.log)

**Comment by isaacrj-scio** [comment]
I read through the patch you sent me and, as far as I can tell, you are applying the fix to every stream, regardless of its codec or interleave-mode. As the h264p and mpeg2i streams where working perfectly with the previous code, maybe if you can detect what type of stream is being decoded, and activate the whole DECODE_ONLY marking and ghost-frame dropping fix to h264 interlaced streams ONLY...

Just my 2 cents :-)

**Comment by dv1** [comment]
Ok, try a more updated version: https://www.dropbox.com/s/5c3f6lxad9hefq7/gstimx-vpu-ghost-frames.diff

**Comment by isaacrj** [comment]
Wow, I'm really impressed with this fix.

Not only do all the video streams play 100% perfect and without leaks now. Also, some strange vsync and audio crackling glitches I was experiencing have disappeared too. 

Nice piece of work. Thank you.

**Comment by dv1** [comment]
Nice! I also didn't see any problems with it so far. I'll consider it done. The fix is obvious now, but as the saying goes, hindsight is 20/20 :)

By the way, I am preparing a separate branch where I refactor the VPU elements to use the imxvpuapi library. This should make the code a lot more maintainable, and make it possible to eventually get rid of the VPU wrapper. This branch won't be merged though until it gets thoroughly tests. Your reports were very helpful in pinpointing an important corner case that I need to take care of in that refactoring as well. So, keep an eye for a new "imxvpuwrapper-intergration" branch in the future.
